[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
markdown = "1.0.0"
clap = { version = "4.5.39", features = ["derive", "env"] }
serde = { version = "1.0.219", features = ["derive"] }
